name: Sync Pipeline

on:
  push:
  workflow_dispatch:

jobs:
  windows-sync:
    runs-on: [self-hosted, Windows, X64]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm install

      - run: npx tsx uber-sync.ts
      - run: npx tsx rocket-sync.ts
      - run: npx tsx menu-sync.ts

  mac-sync:
    runs-on: [self-hosted, macOS, X64]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm install

      - run: npx tsx uber-sync.ts
      - run: npx tsx rocket-sync.ts
      - run: npx tsx menu-sync.ts
