name: Uber Sync

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.yml"
  workflow_dispatch:

jobs:
  uber-sync:
    if: github.actor != 'github-actions[bot]'
    runs-on: [self-hosted, windows]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Restore Uber auth
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force playwright/.auth

          Copy-Item `
            "$env:GITHUB_WORKSPACE\playwright\.auth\user.json" `
            "playwright\.auth\user.json" `
            -Force

      - name: Run Uber Sync
        run: npx tsx uber-sync.ts
